.PHONY: clean All

All:
	@echo "----------Building project:[ racs - Release ]----------"
	@cd "racs" && $(MAKE) -f  "racs.mk"
clean:
	@echo "----------Cleaning project:[ racs - Release ]----------"
	@cd "racs" && $(MAKE) -f  "racs.mk" clean
